# Generated by Django 4.0.4 on 2022-05-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoapi', '0002_populate_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
